#!/usr/bin/env python3
import argparse

BB_NAMES = {"N", "CA", "C", "O", "OXT", "OT1", "OT2", "H", "HA"}
AA_NAMES = { "ALA", "ARG", "ASN", "ASP", "CYS", "GLN", "GLU", "HIS", "ILE", "LEU", "LYS", "MET", "PHE", "PRO", "SER", "THR", "TRP", "TYR", "VAL", "ASH", "GLH", "HIE", "HSE", "HIP", "HSP", "HID", "HSD", "LYN", "CYX", "CYM" }
WATERS = {"HOH", "WAT", "H2O", "DOD"}


def readpdb(path):
 atoms = []
 with open(path) as pdb:
  for line in pdb:
   if not (line.startswith("ATOM") or line.startswith("HETATM")):
    continue
   record = line[0:6].strip()
   atnum = int(line[6:11])
   atnam = line[12:16].strip()
   resnam = line[17:20].strip()
   resnum = int(line[22:26].strip())
   x = float(line[30:38])
   y = float(line[38:46])
   z = float(line[46:54])

   atoms.append({"index": len(atoms),"atnum": atnum,"atnam": atnam, "resnam": resnam, "resnum": resnum,"x": x,"y": y,"z": z,"record": record})
 return atoms

def sdchn(atom):
 return atom["record"] == "ATOM" and atom["resnam"] in AA_NAMES and atom["atnam"] not in BB_NAMES

def water(atom) :
 return atom["resnam"] in WATERS

def other(atom):
 return atom["record"] == "HETATM"

def res_key(atom):
 return (atom["resnum"], atom["resnam"])

def find_neighbors(atoms, residue_numbers, cutoff):
 central_indices = [ a["index"] for a in atoms if a["resnum"] in residue_numbers]
 if not central_indices:
  return []

 coords = [(a["x"], a["y"], a["z"]) for a in atoms]
 center = [coords[i] for i in central_indices]
 neighbors_r = set()

 for atom in atoms:
  if atom["resnum"] in residue_numbers:
   continue

  if not (sdchn(atom) or water(atom) or other(atom)):
   continue

  key = res_key(atom)
  if key in neighbors_r:
   continue

  x, y, z = coords[atom["index"]]

  for (cx, cy, cz) in center:
   dx = x - cx
   dy = y - cy
   dz = z - cz
   if dx * dx + dy * dy + dz * dz <= cutoff**2:
    neighbors_r.add(key)
    break

 neighbors = set()
 for atom in atoms:
  if atom["resnum"] in residue_numbers:
   continue
  if not (sdchn(atom) or water(atom) or other(atom)):
   continue
  if res_key(atom) in neighbors_r:
   neighbors.add(atom["index"])

 return sorted(neighbors)


def squeeze_list(indices):
 if not indices:
  return ""

 indices = sorted(indices)
 ranges = []
 start = prev = indices[0]

 for x in indices[1:]:
  if x == prev + 1:
   prev = x
  else:
   if start == prev:
    ranges.append(str(start))
   else:
    ranges.append("%s-%s"%(start,prev))
   start = prev = x

 if start == prev:
  ranges.append(str(start))
 else:
  ranges.append("%s-%s"%(start,prev))

 return ",".join(ranges)


parser = argparse.ArgumentParser()
parser.add_argument("-p","--pdb", required=True, help="PDB filename")
parser.add_argument("-r","--residues",required=True,nargs="+", type=int, help="Residue number(s)")
parser.add_argument("-d","--distance",required=True,type=float,help="Cutoff distance (A)")
parser.add_argument("-z","--zero",action="store_true",help="Start atom indices from 0 instead of 1 (For Orca)",)

args = parser.parse_args()

atoms = readpdb(args.pdb)

residue_numbers = set(args.residues)
neighbors = find_neighbors(atoms, residue_numbers, args.distance)

if args.zero:
 out = neighbors
else:
 out = [i + 1 for i in neighbors]

print(squeeze_list(out))#!/usr/bin/env python3
import argparse

BB_NAMES = {"N", "CA", "C", "O", "OXT", "OT1", "OT2", "H", "HA"}
AA_NAMES = { "ALA", "ARG", "ASN", "ASP", "CYS", "GLN", "GLU", "HIS", "ILE", "LEU", "LYS", "MET", "PHE", "PRO", "SER", "THR", "TRP", "TYR", "VAL", "ASH", "GLH", "HIE", "HSE", "HIP", "HSP", "HID", "HSD", "LYN", "CYX", "CYM" }
WATERS = {"HOH", "WAT", "H2O", "DOD"}


def readpdb(path):
 atoms = []
 with open(path) as pdb:
  for line in pdb:
   if not (line.startswith("ATOM") or line.startswith("HETATM")):
    continue
   record = line[0:6].strip()
   serial = int(line[6:11])
   name = line[12:16].strip()
   altloc = line[16].strip()
   resname = line[17:20].strip()
   chain = line[21].strip()
   resnum = int(line[22:26].strip())
   icode = line[26].strip()
   x = float(line[30:38])
   y = float(line[38:46])
   z = float(line[46:54])
   if altloc not in ("", " ", "A"):
    continue

   atoms.append({"index": len(atoms),"serial": serial,"name": name, "resname": resname, "chain": chain,"resnum": resnum,"icode": icode,"x": x,"y": y,"z": z,"record": record})
 return atoms


def sdchn(atom):
 if atom["record"] != "ATOM":
  return False
 if atom["resname"] not in AA_NAMES:
  return False
 if atom["name"] in BB_NAMES:
  return False
 return True


def water(atom) :
 return atom["resname"] in WATERS


def other(atom):
 return atom["record"] == "HETATM"


def res_key(atom):
 return (atom["chain"], atom["resnum"], atom["icode"], atom["resname"])


def find_neighbors(atoms, residue_numbers, cutoff):
 central_indices = [ a["index"] for a in atoms if a["resnum"] in residue_numbers]
 if not central_indices:
  return []

 coords = [(a["x"], a["y"], a["z"]) for a in atoms]
 central_coords = [coords[i] for i in central_indices]

 neighbor_residues = set()

 for atom in atoms:
  if atom["resnum"] in residue_numbers:
   continue

  if not (sdchn(atom) or water(atom) or other(atom)):
   continue

  key = res_key(atom)
  if key in neighbor_residues:
   continue

  x, y, z = coords[atom["index"]]

  for (cx, cy, cz) in central_coords:
   dx = x - cx
   dy = y - cy
   dz = z - cz
   if dx * dx + dy * dy + dz * dz <= cutoff**2:
    neighbor_residues.add(key)
    break

 neighbor_indices = set()
 for atom in atoms:
  if atom["resnum"] in residue_numbers:
   continue
  if not (sdchn(atom) or water(atom) or other(atom)):
   continue
  if res_key(atom) in neighbor_residues:
   neighbor_indices.add(atom["index"])

 return sorted(neighbor_indices)


def squeeze_list(indices):
 if not indices:
  return ""

 indices = sorted(indices)
 ranges = []
 start = prev = indices[0]

 for x in indices[1:]:
  if x == prev + 1:
   prev = x
  else:
   if start == prev:
    ranges.append(str(start))
   else:
    ranges.append("%s-%s"%(start,prev))
   start = prev = x

 if start == prev:
  ranges.append(str(start))
 else:
  ranges.append("%s-%s"%(start,prev))

 return ",".join(ranges)


parser = argparse.ArgumentParser()
parser.add_argument("-p","--pdb", required=True, help="PDB filename")
parser.add_argument("-r","--residues",required=True,nargs="+", type=int, help="Residue number(s)")
parser.add_argument("-d","--distance",required=True,type=float,help="Cutoff distance (A)")
parser.add_argument("-z","--zero",action="store_true",help="Start atom indices from 0 instead of 1 (For Orca)",)

args = parser.parse_args()

atoms = readpdb(args.pdb)

residue_numbers = set(args.residues)
neighbor_indices_0 = find_neighbors(atoms, residue_numbers, args.distance)

if args.zero:
   output_indices = neighbor_indices_0
else:
 output_indices = [i + 1 for i in neighbor_indices_0]

print(squeeze_list(output_indices))
